language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
    - set -e
    - npm run lint
    - npm run test

after_success:
  - npm run coveralls
